parsers:
    - crowdsecurity/syslog-logs
    - crowdsecurity/dateparse-enrich
    - crowdsecurity/haproxy-logs
scenarios:
    - ./scenarios/crowdsecurity/my-haproxy-http-bf.yaml
    - ./scenarios/crowdsecurity/my-haproxy-ssl-bf.yaml
postoverflows:
    - ""
log_file: myservice-logs-test.log
log_type: syslog
ignore_parsers: true
